variable "access_key_id" {}
variable "secret_key_id" {}
variable "region" {}
variable "image_id" {}
variable "bastion_vm_type" {}
variable "control_plane_vm_type" {}
variable "control_plane_count" {}
variable "worker_vm_type" {}
variable "worker_count" {}
variable "cluster_name" {}
variable "kubernetes_version" {}
variable "runc_version" {}
variable "containerd_version" {}
variable "etcd_version" {}
variable "cni_version" {}
variable "terraform_os" {}
variable "terraform_arch" {}
variable "with_cloud_provider" {}
variable "with_example_2048" {}
